### ISSUE TITLE
哪里可以找到 instruments 的消息手册？

### ISSUE THREAD

**Issue by guosainpu** [YueChen-C/py-ios-device#12]
我看到各个demo里面会发送各种 instruments 消息来获取相应的数据。例如：rpc.call(channel, "startSamplingForPIDs:", {pid}).parsed
但我找不到instruments都支持哪些消息，还有这些调用这些消息时的传参和返回值的描述。请问有相关的手册吗？

**Comment by doronz88** [comment]
Unfortunately this API is undocumented, but from reversing `DTServiceHub`. As it turns out, you can access all selectors which confirm to `DTXAllowedRPC` protocol. Troy bowman wrote a script to extract this data using Frida.
You can also look here if you're interested in debugging what calls is the `Instruments` utility using the builtin log feature on the device side:

https://github.com/doronz88/pymobiledevice3#comappleinstrumentsremoteserverdvtsecuresocketproxy

**Comment by guosainpu** [comment]
> Unfortunately this API is undocumented, but from reversing `DTServiceHub`. As it turns out, you can access all selectors which confirm to `DTXAllowedRPC` protocol. Troy bowman wrote a script to extract this data using Frida.
> You can also look here if you're interested in debugging what calls is the `Instruments` utility using the builtin log feature on the device side:
> 
> https://github.com/doronz88/pymobiledevice3#comappleinstrumentsremoteserverdvtsecuresocketproxy

Thanks a lot
