### ISSUE TITLE
iOS17设备支持问题

### ISSUE THREAD

**Issue by Nnnnut** [YueChen-C/py-ios-device#124]
大佬求助一下，关于刚更新的 iOS17。
iOS17 对应的 Xcode15 Beta 里没有给出 DeviceSupport 包，现在有办法采集 iOS17 设备的数据吗？

**Comment by YueChen-C** [comment]
没有现在都没有很好的办法，不过可以参考这个库的实现 
https://github.com/doronz88/pymobiledevice3

**Comment by Nnnnut** [comment]
感谢大佬指了一条路，看了一下[pymobiledevice3](https://github.com/doronz88/pymobiledevice3)那边目前在mac上应该是有戏的，想要尝试实现一下，但不得不说咱们两边的库都复杂得很

**Comment by ZhyliaievD** [comment]
Hello
Could you please elaborate more on how should [pymobiledevice3](https://github.com/doronz88/pymobiledevice3) help with iOS 17+ and what actually should be done?

From what I see now, apple no longer provides per-version support files, resulting in py-ios-device attempts to download 17.0.zip files from different souces(with no luck as such files do not exist)

I've tried to simply copy 16.4 files to 17.0 folder, but such a silly option obviously didn't work (due to "ios_device.util.exceptions.StartServiceError: Unable to start service='com.apple.instruments.remoteserver.DVTSecureSocketProxy' - InvalidService" error)

It looks like we need a way to reuse [CoreDevice files](https://developer.apple.com/forums/thread/730947?answerId=756665022#756665022) and use it in py-ios-device?

**Comment by YueChen-C** [comment]
Completed support
